## NumPy Indexing and Selection

In [1]:
import numpy as np

In [3]:
arr = np.arange(0, 11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr[8]

8

In [6]:
arr[1:5]

array([1, 2, 3, 4])

In [7]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [8]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [9]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
arr[0:5] = 100

In [11]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [12]:
arr = np.arange(0, 11)

In [13]:
slice_of_arr = arr[0:5]

In [14]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [15]:
slice_of_arr[:] = 99

In [16]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [17]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [18]:
arr_copy = arr.copy()

In [19]:
arr_copy[:] = 100

In [20]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [21]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [23]:
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

In [24]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [25]:
arr_2d.shape

(3, 3)

In [26]:
arr_2d[0]

array([ 5, 10, 15])

In [27]:
arr_2d[2]

array([35, 40, 45])

In [28]:
arr_2d[1][1]

25

In [29]:
arr_2d[1, 1]

25

In [30]:
arr_2d[0, 2]

15

In [31]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [32]:
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [33]:
arr = np.arange(0, 11)

In [34]:
arr > 4

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [35]:
bool_arr = arr > 4

In [36]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [37]:
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])

In [38]:
len(arr[arr > 4])

6

In [40]:
np.random.randint(0,6, size=6)

array([5, 3, 5, 2, 5, 3])

## NumPy Operations

In [41]:
import numpy as np

In [42]:
arr = np.arange(0, 10)

In [43]:
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [44]:
arr - 2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [45]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [46]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [47]:
arr/arr

<ipython-input-47-50b4ced5627e>:1: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [48]:
arr- arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [49]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [51]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [52]:
np.log(arr)

<ipython-input-52-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [53]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
arr.sum()

45

In [55]:
arr.mean()

4.5

In [56]:
arr.max()

9

In [57]:
arr.std()

2.8722813232690143

In [58]:
arr.var()

8.25

In [61]:
arr2d = np.arange(0, 25).reshape(5, 5)

In [62]:
arr2d.sum()

300

In [63]:
arr2d.sum(axis = 0) ## Across rows

array([50, 55, 60, 65, 70])

In [64]:
arr2d.sum(axis = 1) ## Across columns

array([ 10,  35,  60,  85, 110])

In [65]:
import numpy as np
arr=np.arange(1,37)
arr.shape

(36,)

## In-Class

In [3]:
import numpy as np

In [9]:
x = np.array([1, 2, 3, 99, 99, 3, 2, 1])

In [10]:
np.split(x, [3,5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [11]:
a, b, c = np.split(x, [3, 5])

In [12]:
a

array([1, 2, 3])

In [13]:
b

array([99, 99])

In [14]:
c

array([3, 2, 1])

In [17]:
np.split(x, 4)

[array([1, 2]), array([ 3, 99]), array([99,  3]), array([2, 1])]

In [18]:
m = np.arange(20).reshape(5, 4)

In [19]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [30]:
np.vsplit(m,[1])

[array([[0, 1, 2, 3]]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])]

In [31]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [43]:
np.hsplit(m, [3])

[array([[ 0,  1,  2],
        [ 4,  5,  6],
        [ 8,  9, 10],
        [12, 13, 14],
        [16, 17, 18]]),
 array([[ 3],
        [ 7],
        [11],
        [15],
        [19]])]

#### Sorting of the Arrays

In [49]:
v = np.array([2,1,4,3,5])

In [50]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [51]:
v

array([2, 1, 4, 3, 5])

In [52]:
v.sort()

In [53]:
v

array([1, 2, 3, 4, 5])

In [54]:
twoD = np.random.randint(5,100,(3,3))
twoD

array([[21, 89, 45],
       [49, 88, 82],
       [55, 92, 55]])

In [55]:
np.sort(twoD) # Sorted in rows - not in whole matrix

array([[21, 45, 89],
       [49, 82, 88],
       [55, 55, 92]])

In [56]:
np.sort(twoD, axis = 0) # Ordered based on columns

array([[21, 88, 45],
       [49, 89, 55],
       [55, 92, 82]])

In [57]:
np.sort(twoD, axis = 1) # Ordered based on rows

array([[21, 45, 89],
       [49, 82, 88],
       [55, 55, 92]])

In [58]:
arr = np.arange(0,11)

In [59]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [61]:
arr[8]

8

In [62]:
arr[-1]

10

In [63]:
arr[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [64]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [74]:
arr[:3] = 99

In [75]:
arr

array([99, 99, 99,  3,  4,  5,  6,  7,  8,  9, 10])

In [76]:
a = arr.copy()

In [77]:
a[:3] = 100

In [78]:
a

array([100, 100, 100,   3,   4,   5,   6,   7,   8,   9,  10])

In [79]:
arr

array([99, 99, 99,  3,  4,  5,  6,  7,  8,  9, 10])

In [80]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [86]:
arr_2d[0:3,0]

array([ 5, 20, 35])

In [87]:
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [88]:
arr_2d[:,1]

array([10, 25, 40])

In [89]:
arr_2d[0,0] = 3.3

In [90]:
arr_2d

array([[ 3, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

### Fancy Indexing

In [91]:
v = np.arange(0, 30, 3)

In [92]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [93]:
v[3]

9

In [94]:
id_list = [1, 3, 5]

In [95]:
v[id_list]

array([ 3,  9, 15])

In [107]:
arr2d = np.zeros((10, 10), dtype=int)
arr2d



array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [108]:
arr_length = 10
for i in range(arr_length):
    arr2d[i] = i
arr2d

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

In [110]:
arr2d[[2,4,6,8], 2:5]

array([[2, 2, 2],
       [4, 4, 4],
       [6, 6, 6],
       [8, 8, 8]])

In [4]:
jj = np.arange(1,17).reshape((4,4))

In [112]:
jj

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [113]:
jj[[1,2],[0,3]]

array([ 5, 12])

In [114]:
jj[[0,2,3],[0,1,3]]

array([ 1, 10, 16])

In [118]:
jj[:,[1,2]]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [6]:
jj[1:3,[1,2]]

array([[ 6,  7],
       [10, 11]])

In [7]:
jj[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

In [8]:
arr = np.arange(1,11)

In [9]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
arr < 4

array([ True,  True,  True, False, False, False, False, False, False,
       False])

In [11]:
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])

In [12]:
v = np.array([1, 2, 3, 4, 5])
v

array([1, 2, 3, 4, 5])

In [13]:
v[3] = v[3] + 1

In [14]:
v

array([1, 2, 3, 5, 5])

In [15]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
# Claculating karakok
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [18]:
# Calculating exponential (e^)
np.exp(arr)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [19]:
np.max(arr)

10

In [20]:
arr.max()

10

In [21]:
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [22]:
np.cos(arr)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        0.96017029,  0.75390225, -0.14550003, -0.91113026, -0.83907153])

In [23]:
np.cos(100)

0.8623188722876839

In [24]:
np.sin(np.pi)

1.2246467991473532e-16

In [25]:
np.pi

3.141592653589793

In [26]:
np.subtract(v,1)

array([0, 1, 2, 4, 4])

In [27]:
np.subtract(v,1)

array([0, 1, 2, 4, 4])

In [28]:
x1 = np.arange(9.0).reshape((3, 3))
x2 = np.arange(3.0)

In [29]:
np.subtract(x1,x2)

array([[0., 0., 0.],
       [3., 3., 3.],
       [6., 6., 6.]])

In [30]:
np.add(v,1)

array([2, 3, 4, 6, 6])

In [33]:
np.multiply(v,4)

array([ 4,  8, 12, 20, 20])

In [34]:
np.divide(v,2)

array([0.5, 1. , 1.5, 2.5, 2.5])

In [35]:
np.power(v,2)

array([ 1,  4,  9, 25, 25], dtype=int32)

In [37]:
np.absolute(np.array([-4]))

array([4])

### Statistical Calculation

In [38]:
v = np.array([1,1,2,2,3,3,3,3])
v

array([1, 1, 2, 2, 3, 3, 3, 3])

In [39]:
np.mean(v)

2.25

In [40]:
np.median(v)

2.5

In [42]:
np.sum(v)

18

In [43]:
v.sum()

18

In [44]:
v.min()

1

In [45]:
np.min(v)

1

In [46]:
v.max()

3

In [47]:
np.var(v)

0.6875

In [48]:
np.std(v)

0.82915619758885

In [50]:
np.corrcoef(v)

1.0

AttributeError: 'numpy.ndarray' object has no attribute 'corrcoef'